### DISCUSSION TITLE
Feature request: Add Ability to Mark Specific Tests as Needing Retries

### DISCUSSION THREAD

**Discussion by cwfitzgerald** [nextest-rs/nextest#1773] [Feature requests]
### Motivation

I have one specific test that is known flaky and needs a few retires, but I don't want to allow other tests to _get_ flaky.

### Proposal

Add `retry-count` or similar to the per-test configuration.

### Alternatives

None

**Comment by sunshowers** [comment]
Ah -- retries are definitely supported:

```toml
[[profile.ci.overrides]]
filter = 'test(/\btest_network_/)'
retries = 4
```

But https://nexte.st/docs/configuration/per-test-overrides/ accidentally didn't mention them -- will fix that.
