### DISCUSSION TITLE
How to configure nextest to use a custom cargo profile with Cranelift backend?

### DISCUSSION THREAD

**Discussion by 39george** [nextest-rs/nextest#2338] [Q&A] [answered]
Hello! I'm using Cranelift as my codegen backend during development. I've set up a custom profile in `.cargo/config.toml`:
```toml
[unstable]
codegen-backend = true

[target.x86_64-unknown-linux-gnu]
rustflags = ['--cfg=curve25519_dalek_backend="serial"']

[profile.custody-dev]
inherits = "dev"
codegen-backend = "cranelift"
```
I run my binaries with:
```bash
cargo run --profile custody-dev
```

I need this custom profile because cargo-llvm-cov doesn't work with Cranelift (it requires LLVM for coverage instrumentation). However:
Regular nextest works fine with Cranelift.
For coverage, I use cargo llvm-cov nextest (which automatically uses LLVM).

Question:
How can I configure nextest to use my custody-dev profile (with Cranelift) for regular testing, while keeping LLVM only for coverage runs?
