### ISSUE TITLE
Proposed design for including extra files in the archive

### ISSUE THREAD

**Issue by rukai** [nextest-rs/nextest#1340]
Maintainer edit, tracking TODOs:

- [x] Add optional depth param, and limit depth by default to a reasonable value (we've chosen 8): https://github.com/nextest-rs/nextest/pull/1411
- [x] Warn if a path isn't present (may allow this to be configured as required or skipped in the future) -- also warn if a depth = 0 is a directory, which is a similar situation: https://github.com/nextest-rs/nextest/pull/1451
- [x] Check that path is well-formed: https://github.com/nextest-rs/nextest/pull/1454
- [x] Add test for skipped file types (not file, dir or symlink): https://github.com/nextest-rs/nextest/pull/1451
- [x] For errors, indicate why we're deciding to include a file in the archive (using an enum): https://github.com/nextest-rs/nextest/pull/1454
- [x] Write docs: https://github.com/nextest-rs/nextest/commit/f74d29954614a5764f8f6465175197c63d4234f3

---

From reading the discussion in https://github.com/nextest-rs/nextest/issues/423 it sounds like a feature like this is welcome.
But I wanted to make a proposal for a design before I set about implementing it.

I propose that we add the following configuration options to the config file and they will behave as documented.
```toml
# `nextest archive` automatically includes any build output required by a standard build.
# However sometimes extra non-standard files are required.
# "archive-include-within-target" specifies additional paths that will be included in the archive.
#
# Example: archive-include-within-target = ["application-data", "data-from-some-dependency/file.txt"]
# In this example:
# * the directory and its contents at "target/application-data" will be included in the archive.
# * the file "target/data-from-some-dependency/file.txt" will be included in the archive.
archive-include-within-target = []

# "archive-include-within-target-profile" provides an additional list of paths within the
# current cargo profile to include.
#
# Example: archive-include-within-target-profile = ["application-data", "data-from-some-dependency/file.txt"]
# In this example when compiling with the release profile:
# * the directory and its contents at "target/release/application-data" will be included in the archive
# * the file "target/release/data-from-some-dependency/file.txt" will be included in the archive.
archive-include-within-target-profile = []
```

I believe that these 2 config options should cover all possible use cases.

Alternatively we could have a single config option and support `*` globbing for profile specific paths. e.g. `*/application-data`
But that would mean that both release and debug builds would be included.

This design intentionally does not intend to add CLI flags for this as it feels like a build configuration level problem and not something the user would want ad-hoc control over.

But @sunshowers did mention including CLI flags for it in #423 , so maybe there is a motivation I'm missing.
