### ISSUE TITLE
Test Suite Running Very Slowly

### ISSUE THREAD

**Issue by seanpianka** [nextest-rs/nextest#1573]
Lately, I am experiencing significantly slow test execution times using nextest + [llvm-cov](https://github.com/taiki-e/cargo-llvm-cov). Below is an example of a single test and its execution time.

#### Test Example

```rust
#[test]
fn test_auth_req_schema_serialize() {
    let auth_req = Authenticate {
        method: AuthenticateMethod::Password(UserPassAuthenticate {
            email: "sadf.com".to_string(),
            password: "password".to_string(),
        }),
    };
    let serialized = serde_json::to_string(&auth_req).unwrap();
    assert_eq!(
        serialized,
        "{\"method\":{\"Password\":{\"email\":\"sadf.com\",\"password\":\"password\"}}}"
    );
}
```

#### Execution Time

From one invocation, the above test takes an excessively long time to execute:

```
PASS [  42.921s] app-users-types commands::tests::test_auth_req_schema_serialize
```

#### Environment

- **Nextest Version**: 0.9.67
- **Rust Version**: 1.79.0
- **OS**: Alpine 3.19, the container environment is `docker:26.1.3-dind-alpine3.19`, runs within GitLab CI on a self-managed runner (hardware: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, 32GB of DDR4 memory)

#### Steps to Reproduce

1. Create a new Rust project.
2. Add the following dependencies to `Cargo.toml`:
    ```toml
    [dependencies]
    serde = { version = "1", features = ["derive"] }
    serde_json = "1"
    ```
3. Create the following test in `src/lib.rs`:
    ```rust
    #[cfg(test)]
    mod tests {
        use serde::{Deserialize, Serialize};

        #[derive(Serialize, Deserialize)]
        struct UserPassAuthenticate {
            email: String,
            password: String,
        }

        #[derive(Serialize, Deserialize)]
        struct Authenticate {
            method: AuthenticateMethod,
        }

        #[derive(Serialize, Deserialize)]
        enum AuthenticateMethod {
            Password(UserPassAuthenticate),
        }

        #[test]
        fn test_auth_req_schema_serialize() {
            let auth_req = Authenticate {
                method: AuthenticateMethod::Password(UserPassAuthenticate {
                    email: "sadf.com".to_string(),
                    password: "password".to_string(),
                }),
            };
            let serialized = serde_json::to_string(&auth_req).unwrap();
            assert_eq!(
                serialized,
                "{\"method\":{\"Password\":{\"email\":\"sadf.com\",\"password\":\"password\"}}}"
            );
        }
    }
    ```
4. Run the test using Nextest and observe the execution time.

#### Additional Information

- **Command**: 
```bash
  cargo llvm-cov nextest \
      --locked \
      --config-file ./.config/nextest.toml \
      --features test_database_backing_impl \
      --bins --examples --tests --all-targets \
      --no-fail-fast \
      --no-report \
      --workspace
```
- **Config**:
```toml
# This section defines the default nextest profile. Custom profiles are layered
# on top of the default profile.
[profile.default]
slow-timeout = { period = "60s", terminate-after = 3 }

[profile.default.junit]
# Output a JUnit report into the given file inside 'store.dir/<profile-name>'.
# If unspecified, JUnit is not written out.
path = "results.xml"

# The name of the top-level "report" element in JUnit report. If aggregating
# reports across different test runs, it may be useful to provide separate names
# for each report.
report-name = "nextest-run"
```

- **Other Tests**:

This test is run within a suite of 415 other tests, however the execution time of the other tests varies wildly. The other tests, which are at the same level of complexity (read: very simple methods set a boolean field from false to true and assert it as such), take different amounts of time and do not appear consistent.

```
        PASS [  20.025s] domain-users account::password_reset_attempt::tests::should_fail_to_create_reset_pin_of_invalid_length
        PASS [  11.661s] domain-users account::password_reset_attempt::tests::should_fail_to_create_reset_pin_with_invalid_chars
        PASS [   4.373s] domain-users account::password_reset_attempt::tests::should_show_a_new_password_reset_attempt_is_inactive
        PASS [   0.883s] domain-users account::tests::should_authenticate_active_account
        PASS [   3.451s] domain-users account::tests::should_activate_inactive_account
        PASS [   0.981s] domain-users account::tests::should_change_email
        PASS [  10.898s] domain-users account::tests::should_change_active_account_to_the_same_password_and_authenticate
```

Arbitrary groupings of different tests (i.e. unstable, fast and slow groupings change between invocations) that run within 0.x seconds, while tests of the same complexity within the same module will take 60s+ to run. The same test will take different amounts of time to run between invocations of nextest run.

Please let me know if you need any further information or additional logs.

Thank you for your help!
