### ISSUE TITLE
Add support for doctests

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#16]
Should be possible if we grab the doctest executables through `-Z unstable-options --persist-doctests`. However, this isn't a stable approach so it must be used with care.

**Comment by xd009642** [comment]
So I use the `--persist-doctests` attribute and can share some of the issues I've faced with it, (hopefully more people using it will lead to stabilisation and improvements). So if we have a doctest with the `should_panic` attribute `cargo test` compiles and runs it and checks if the return code is non-zero, and the test passes only if it's non-zero. 

However, the doctest file name is made from a normalisation of the path (all path separators replaced with `_`, a line number and a number to ensure the files are unique. This is because a doctest on the same line in `src/foo/bar.rs` and `src/foo_bar.rs` would otherwise generate the same filename. The line numbers are also done after macro expansion so things like `include_str` can make it harder to match line numbers with attributes.

I made an issue in rust about bundling attribute information into the file name to make it easier for people writing tools using this feature https://github.com/rust-lang/rust/issues/92597 and if you're interested in seeing my code it's in https://github.com/xd009642/tarpaulin in `src/cargo.rs`, it's reasonably stable the issues mentioned above are the only parts it can fail. I've had this since the nightly flag was created and the naming convention has only changed once so I've only had one completely unexpected issue that affected all users that cause persist-doctests to be added.

Hope this is helpful, nextest looks pretty nifty :tada:

**Comment by nu11ptr** [comment]
Can I suggest that until this is added this is called out in the docs in a visible way? I recently was made aware how tricky doctests are to handle, but other users might not be aware. Your crate looks like it could be nice (I can't test rn, this crate is doctest only) and it would be a shame if they didn't give it a fair chance because they thought it was broken.

**Comment by sunshowers** [comment]
@nu11ptr good idea -- I've added a note to the homepage along with expanding the notes on the listing and running pages https://github.com/nextest-rs/nextest/commit/f4043b17a080533e52b94d6ae11743144318ed75

**Comment by tgross35** [comment]
Rustdoc may gain the unstable flag `--extract-doctests` which will provide a way to list doctests with their attributes and contents. Is this something that `nextest` could make use of? https://github.com/rust-lang/rust/pull/134531

**Comment by tgross35** [comment]
Separately, would it be possible for nextest to just run `cargo test --doc` itself after running other tests? Even without the nice UI it would eliminate the footgun, as well being less to remember/type when running locally.

Of course `--extract-doctests` or similar would make this unnecessary, but it seems like an easy stopgap until that is usable on stable. (For the record, I would still be quite happy if nextest can run doctests directly only on nightly).

**Comment by aDotInTheVoid** [comment]
> Is this something that nextest could make use of? https://github.com/rust-lang/rust/pull/134531

From a rustdoc perspecive, we defiantly want nextest to be able to use this, and if it can't that's a flaw with rustdoc's thing, and we'd love to hear about this. Ideally, I'd love to see nextest use this (as an experimental feature) _before_ it gets stabilized, to give us some confidence it's broadly useful

**Comment by epage** [comment]
Cargo wants to have `--doc` flags on every build command (`cargo check --doc`) to build doc tests. I'd recommend playing with `--extract-doctests` inside of cargo to add support for `--doc`  so it can generate the doctest binaries for you with build caching and correct linking (which was brittle when people tried to do this for READMEs in the past).

**Comment by sunshowers** [comment]
This would be really nice to have -- I don't expect to have any time to work on it soon, but some assistance (maybe a prototype within nextest) would be greatly appreciated.

**Comment by skull-squadron** [comment]
As a hackaround, run doctests with `cargo test`. For example: run`cargo make nextest`. I prefer to run it TDD style with [`bacon`](https://dystroy.org/bacon).

```toml
# Makefile.toml

[tasks.test]
clear = true
workspace = false
dependencies = ["test-tests", "test-doctests"]

[tasks.nextest]
clear = true
workspace = false
dependencies = ["nextest-tests", "test-doctests"]

[tasks.nextest-tests]
workspace = false
command = "cargo"
args = ["nextest", "run", "--workspace", "--hide-progress-bar", "--failure-output", "final"]

[tasks.test-tests]
workspace = false
command = "cargo"
args = ["test", "--all-targets", "--all-features", "--workspace"]

[tasks.test-doctests]
workspace = false
command = "cargo"
args = ["test", "--all-features", "--doc", "--workspace"]
````
