### ISSUE TITLE
`cargo nextest` fails to archive for `aarch64-apple-darwin` when there is a windows-only dependency on `windows-rs` 0.40+

### ISSUE THREAD

**Issue by poliorcetics** [nextest-rs/nextest#553]
Reproducer:

```toml
[package]
name = "nextest-reproducer"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
# windows = "0.39.0" # Works
windows = "0.40.0" # This and below fails
# windows = "0.41.0"
# windows = "0.42.0"
```

```rust
fn main() {
    println!("Hello, world!");
}
```

Building works:

```
cargo clean; cargo build --all-targets --target aarch64-apple-darwin --release --workspace

   Compiling nextest-reproducer v0.1.0 ([CWD]/nextest-reproducer)
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
```

But `cargo nextest archive` doesn't:

```
cargo clean; cargo nextest archive --target aarch64-apple-darwin --release --workspace --archive-file "target/tests.tar.zst"

error: error parsing Cargo metadata

Caused by:
  failed to construct package graph: for package 'windows 0.40.0 (registry+https://github.com/rust-lang/crates.io-index)': for dependency 'windows_aarch64_gnullvm', parsing target 'aarch64-pc-windows-gnullvm' failed: unknown target triple
```

## Meta

- Fails on both a M1 Mac and a Linux CI
- `cargo nextest --version`: `0.9.36`

```
rustc -Vv

rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: aarch64-apple-darwin
release: 1.64.0
LLVM version: 14.0.6
```

```
cargo -Vv

cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: aarch64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```
