### ISSUE TITLE
profile with retries = 0 doesn't work

### ISSUE THREAD

**Issue by xxchan** [nextest-rs/nextest#622]
```toml
[profile.default]
retries = 5

[profile.ci]
retries = 0
```

`cargo nextest run -P ci` will retry 5 times instead of 0 times. In an older version `0.9.23` (quite old...) it works correctly.
