### ISSUE TITLE
Leaky tests hang on Windows

### ISSUE THREAD

**Issue by chipsenkbeil** [nextest-rs/nextest#656]
This seems to only happen on Windows, but nextest hangs after all tests have run. I have a lot of leaky tests because I'm spawning a cli that runs for the entire test run and I cannot kill it until I do so manually as part of my ci.

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/2481802/202329153-d81c4f32-d344-46ce-bdb1-f21dda91062f.png">

Is there something I can do to determine why it's hanging only on Windows? Anything I can do to prevent the hanging?

---

`.config/nextest.toml`

```toml
[profile.ci]
fail-fast = false
retries = 2
slow-timeout = { period = "60s", terminate-after = 3 }
status-level = "fail"
final-status-level = "fail"
```
