### ISSUE TITLE
Can't get `threads-required` working

### ISSUE THREAD

**Issue by azzamsa** [nextest-rs/nextest#715]
Hi, I have spent an hour to get it right. Reading [Configuration](https://nexte.st/book/configuration.html) and [Heavy tests and threads-required ](https://nexte.st/book/threads-required.html) but have no luck.

As My [initial question](https://github.com/nextest-rs/nextest/issues/621#issue-1434046167). I want to limit the `--test-threads` only for `user::` test.

This is my initial command. It works well

```shell
$ cargo nextest run --all-targets --test-threads 1
```

But this doesn't work (the tests still runs on parallel)

```toml
[[profile.default.overrides]]
filter = 'test(user::)'
threads-required = 1
```

```shell
$ cargo nextest run --config-file configs/nextest.toml
```

Am I missing something?
