### ISSUE TITLE
threads-required = "num-test-threads" may not be working on macos

### ISSUE THREAD

**Issue by jeromegn** [nextest-rs/nextest#831]
We have a CI building for both Linux and macOS. There's a test we need to run sequentially because it affects a global state.

The way we do this is with a `./config/nextest.toml` containing:

```toml
[profile.ci]
slow-timeout = "180s"
failure-output = "final"
fail-fast = false

[profile.ci.junit]
path = "junit.xml"

[[profile.ci.overrides]]
filter = "test(~wswg)"
threads-required = "num-test-threads"
```

Under Linux, it seems like it is doing the right thing, if I look at the junit output:

```xml
<testcase name="deploy_basic_node_app_w_wswg" classname="testflight::deploy_test" timestamp="2023-03-14T14:42:41.236+00:00" time="100.707"> </testcase>
<testcase name="machine_run" classname="testflight::deploy_test" timestamp="2023-03-14T14:44:21.947+00:00" time="5.915"> </testcase>
```

Under macOS:

```xml
<testcase name="deploy_basic_node_app_w_wswg" classname="testflight::deploy_test" timestamp="2023-03-14T14:42:41.039+00:00" time="110.462"> </testcase>
<testcase name="deploy_basic_node_app_w_remote_builder" classname="testflight::deploy_test" timestamp="2023-03-14T14:42:41.038+00:00" time="184.399"> 
```

On Linux, the tests are ran one after the other because the `~wswg` test uses all available test threads. I figured that out based on the timestamps and time to run the `~wswg` test.

On macOS, the tests are ran at the same time (again, based on the timestamps).

Did I configure it wrong?
